### ISSUE TITLE
deer-pipe 接受艾特全体的参数时报错

### ISSUE THREAD

**Issue by shangxueink** [shangxueink/koishi-shangxue-apps#15]
得到`🦌 <at type="all"/>`的输入的时候会`发生未知错误。`
```
2024-10-10 12:41:00 [W] command 🦌 <at type="all"/>
                        Error: missing primary key
                            at Proxy.create (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\minato\src\database.ts:514:17)
                            at Object.apply (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@cordisjs\core\src\utils.ts:141:40)
                            at Object.apply (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@cordisjs\core\src\utils.ts:141:40)
                            at _Command.<anonymous> (d:\QQbots\QQ_bots\koishing\coding\koishi-app\external\deer-pipe\src\index.ts:137:28)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at Array.<anonymous> (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@koishijs\core\src\command\command.ts:291:14)
                            at _Command.execute (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@koishijs\core\src\command\command.ts:307:22)
                            at <anonymous> (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@koishijs\core\src\session.ts:443:22)
                            at Proxy.withScope (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@koishijs\core\src\session.ts:342:22)
                            at next (D:\QQbots\QQ_bots\koishing\coding\koishi-app\node_modules\@koishijs\core\src\middleware.ts:258:16)
```

**Comment by shangxueink** [comment]
1.2.0 修复
