### ISSUE TITLE
BV号异常

### ISSUE THREAD

**Issue by Evander0** [shangxueink/koishi-shangxue-apps#20]
使用onebot适配器，插件全部最新

2024-10-11 13:23:23 [I] original-message-log BV1sW1oY9Eyd
2024-10-11 13:23:23 [W] session BV1sW1oY9Eyd
                        TypeError: Cannot read properties of null (reading 'includes')
                            at handleBilibiliMedia (/koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:787:23)
                            at processVideoFromLink (/koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:349:58)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async /koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:119:17
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)

**Comment by shangxueink** [comment]
复现了，是bug

**Comment by shangxueink** [comment]
0.6.3 版本修复了 过会更新一下
