### ISSUE TITLE
@shangxueink/koishi-plugin-keyword-dialogue 部分关键词无法添加

### ISSUE THREAD

**Issue by shangxueink** [shangxueink/koishi-shangxue-apps#3]
我发现了有一组问答添加的有问题
```
添加 -x  Ciallo～(∠・ω< )⌒☆

请输入回复内容（输入 取消添加 以取消，输入 结束添加 以结束）：

柚子厨

关键词 "ciallo～(∠・ω<" 的回复已添加。

```

然后我们添加进入json的内容是这样的
```
{
  "regex:ciallo～(∠・ω<": [
    [
      {
        "type": "text",
        "text": "柚子厨"
      }
    ]
  ]
}
```

暂且先不看这个添加的关键词不对，只要能触发就行，问题是现在触发不了，我看到日志有报错
```
2024-09-25 16:59:54 [W] session 已经爆炸了呢
                        SyntaxError: Invalid regular expression: /ciallo～(∠・ω</: Unterminated group
                            at new RegExp (<anonymous>)
                            at checkAndSendRandomReply (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@shangxueink\koishi-plugin-keyword-dialogue\lib\index.js:707:27)
                            at middlewareFunction (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@shangxueink\koishi-plugin-keyword-dialogue\lib\index.js:729:64)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async next (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (C:\Users\shangxue\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)

```

这看起来是一个json格式的报错的问题什么的

**Comment by shangxueink** [comment]
0.6.3 版本已修复

删除关键词后，重新添加即可
