### ISSUE TITLE
【bilibili-videolink-analysis】 发送视频错误： retcode: 1200

### ISSUE THREAD

**Issue by cn1095** [shangxueink/koishi-shangxue-apps#44]
ntqq
onebot设置超时 60000毫秒了
然后发送视频失败

```shell

"message":[{"type":"video","data":{"file":"https://cn-sccd-ct-01-29.bilivideo.com/upgcxcode/83/24/981432483/981432483-1-16.mp4?e=ig8euxZM2rNcNbRVhwdVhwdlhWdVhwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1730617771&gen=playurlv2&os=bcache&oi=1848130790&trid=0000ee25cb44fe2746aa896350ce3acc2f69h&mid=0&platform=html5&og=cos&upsig=37528384a179fcd7f96fc39d854ed60b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=62629&bvc=vod&nettype=0&f=h_0_0&bw=50996&logo=80000000","cache":0}}]}, retcode: 1200
                            at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:162:20)
                            at async OneBotMessageEncoder.flush (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:763:330)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:620:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:355:22)
                            at async sendVideoWithRetry (/koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:581:23)
                            at async processVideoFromLink (/koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:610:41)
                            at async /koishi/node_modules/koishi-plugin-bilibili-videolink-analysis/lib/index.js:125:17
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:824:16)

```

**Comment by shangxueink** [comment]
> retcode: 1200

查看你的协议端日志 

往往这与 koishi 无关

**Comment by cn1095** [comment]
我试着加了 发送失败进行重试5次  都发不过去

llonebot
![图片](https://github.com/user-attachments/assets/291c7ca1-67ed-4710-836f-18c759584deb)
看来是llonebot或者koishi的onebot哪里中断了下载吧

**Comment by cn1095** [comment]
![图片](https://github.com/user-attachments/assets/f5943bb1-170c-4127-9f2c-404c114ee823)
自己加了个进行五次 发送失败重试的检测后  除了太长的视频 基本可以发送了
