### ISSUE TITLE
@shangxueink/koishi-plugin-keyword-dialogue 无法设置管理员

### ISSUE THREAD

**Issue by Lsoland** [shangxueink/koishi-shangxue-apps#7]
如果设置Only_admin_auth为开启,无法使用任何权限(自动回复正常),提示发生未知错误,日志报错
{"id":386,"type":"warn","level":2,"name":"command","meta":{},"content":"添加 1\nTypeError: Cannot read properties of undefined (reading 'roles')\n    at isAdmin (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@shangxueink\\koishi-plugin-keyword-dialogue\\lib\\index.js:325:47)\n    at _Command.<anonymous> (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@shangxueink\\koishi-plugin-keyword-dialogue\\lib\\index.js:882:38)\n    at Array.<anonymous> (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:1078:27)\n    at argv.next (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:1089:30)\n    at _Command.execute (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:1092:33)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:2059:22\n    at async Proxy.withScope (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:1968:22)\n    at async next (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:824:16)\n    at async next (C:\\Users\\27212\\AppData\\Roaming\\Koishi\\Desktop\\data\\instances\\default\\node_modules\\@koishijs\\core\\lib\\index.cjs:824:16)","timestamp":1728060427368}
如果关闭,仅仅添加管理员,将ID设置为qq号,那么会被认为是0,未能设置管理员,只能用0的权限,提示没有权限

**Comment by shangxueink** [comment]
运行环境，使用的适配器是什么

**Comment by Lsoland** [comment]
> 运行环境，使用的适配器是什么

windows官网下载的1.1.3koishi,适配器是自带的adapter-qq

**Comment by shangxueink** [comment]
目前adapter-qq不支持获取群员角色（非回调按钮方法），并且也不支持获取群员QQ号

本插件主要面向用户为 adapter-onebot 

---

请关闭`Only_admin_auth`配置项，并且开启`inspect`插件，发`/inspect`指令，查看你自己的USERID

然后填写到`admin_list`下

**Comment by Lsoland** [comment]
> st

已解决,谢谢
